### ISSUE TITLE
[ci] Add CI check for migrations

### ISSUE THREAD

**Issue by marfgold1** [openwisp/django-loci#12]
Add CI check for migrations with [this solution](https://github.com/openwisp/openwisp-users/pull/35/files) for ensuring the migrations created have have been renamed to something more descriptive like [this GCI task says](https://codein.withgoogle.com/dashboard/task-instances/5806059705860096/).

**Comment by marfgold1** [comment]
Hello @atb00ker @nemesisdesign ! 
I want to ask about this issue.
In the `runcheckmigration` file in [the solution provided](https://github.com/openwisp/openwisp-users/pull/35/files), i found this line:
```
checkmigrations --migrations-to-ignore 2 \
			   --migration-path ./tests/testapp/migrations/ || exit 1
```
I did observe a little bit, and found out that `django-loci` **does not** have `./tests/testapp/migrations/` path in it. Should i remove that line or what?
And last, this line:
```
checkmigrations --migrations-to-ignore 3 \
			   --migration-path ./openwisp_users/migrations/ || exit 1
```
Should i replace `openwisp_users` to `django_loci`?
Thank you very much :)

**Comment by EdgeKing810** [comment]
Try to take a look at what I did and try to understand...

https://github.com/openwisp/django-ipam/pull/57

**Comment by atb00ker** [comment]
@marfgold1 those lines are for that repository, for this repository you will obviously need and test if everything is working here. :smile: 
Remember: Don't copy the lines, make them work on your system and ensure that it's correct, that example in the task is just for reference. :smile:

**Comment by marfgold1** [comment]
Yeah i already pull request and commit about it, would you like to review my PR @atb00ker ? Thanks

**Comment by atb00ker** [comment]
There is already a review! Please check it. :smile:

**Comment by marfgold1** [comment]
> There is already a review! Please check it. 😄

Done 👍
