### ISSUE TITLE
[ux] isMobile UI inconsistency

### ISSUE THREAD

**Issue by marfgold1** [openwisp/django-loci#34]
In add/change device, when user toggle on `isMobile`, then related fields (location, address, and geometry) should be hidden. But when user change the `Type` while leaving `isMobile` toggled on, it will show the related fields again, even though `isMobile` is still toggled on. The expected result is the related fields should be stay hidden.

**Comment by nemesisdesign** [comment]
@marfgold1 could you please test again this issue on the latest master and let us know if the issue still happens? Last time I tried it looked solved. If the problem does not show up anymore, please close  this.

**Comment by marfgold1** [comment]
@nemesisdesign It's still happens on the latest master.
When isMobile checked, the fields are gone:
![Screenshot from 2019-12-21 23-44-46](https://user-images.githubusercontent.com/34912365/71310872-0a786c00-244c-11ea-9b97-bdb4714662d7.png)

But when I change the type, the fields are back, even though isMobile is still checked:
![Screenshot from 2019-12-21 23-44-51](https://user-images.githubusercontent.com/34912365/71310881-20862c80-244c-11ea-834e-c9a33edf2786.png)

**Comment by marfgold1** [comment]
@nemesisdesign It's still happens on the latest master.
When isMobile checked, the fields are gone:
![Screenshot from 2019-12-21 23-44-46](https://user-images.githubusercontent.com/34912365/71310872-0a786c00-244c-11ea-9b97-bdb4714662d7.png)

But when I change the type, the fields are back, even though isMobile is still checked:
![Screenshot from 2019-12-21 23-44-51](https://user-images.githubusercontent.com/34912365/71310881-20862c80-244c-11ea-834e-c9a33edf2786.png)

And yes I'm on the latest master:
![Uploading Screenshot from 2019-12-21 23-50-19.png…]()

**Comment by nemesisdesign** [comment]
Ok thanks for the update! :+1:

**Comment by nemesisdesign** [comment]
I created a GCI task for this.
