### ISSUE TITLE
[ux] Floorplan fields is shown when error occurs in new indoor environment

### ISSUE THREAD

**Issue by marfgold1** [openwisp/django-loci#35]
To produce this, follow these steps:
1. Add device, leave some fields empty (especially the required one: name, organization and mac address) to produce error when saving.
2. In `Geographic Information` secton, set `Location selection` to **New** and set Type to **Indoor environment**
3. In `Indoor Coordinates` section, select file to the Image field, and set the position for Indoor (you can just use dummy image and set position anywhere) to bypass the client indoor position validation.
4. Save the device.
5. In `Indoor Coordinates` section, you can see the `Floorplan section` and `Floorplan` fields is showed.

The expected output: Floorplan fields should be hidden (You can change the type to Outdoor and change it again to Indoor, then you see Floorplan fields is hidden again).
Additional note: The Floorplan fields should be showed **only in existing location**

**Comment by nemesisdesign** [comment]
Summary: the floorplan field should not be shown.

**Comment by waleko** [comment]
@nemesisdesign Should the floorplan field always be hidden when device isn't created yet? Meaning you can't create a device with a new indoor location with a new floorplan from one single changeview? Did I misunderstand it?
