### ISSUE TITLE
[ux] Location selection hidden when error occurs while isMobile toggled on

### ISSUE THREAD

**Issue by marfgold1** [openwisp/django-loci#36]
To produce this issue, follow this step:
1. Add device, leave some fields empty. (MAC, Name)
2. Set `Location selection` to `New`
3. Set `Type` to `Outdoor environment`
4. Toggle `isMobile` to true.
5. Save device

On the form error page, we see "Location data not received yet" and the isMobile check box is hidden.

Expected output: Location selection & isMobile field should be showed.
Additional note: Leaving isMobile to false will show the field, though. It's also occurs in Indoor environment, existing location selection, and even in the change device form, as long as isMobile is toggled on and there is error when saving.

**Comment by atb00ker** [comment]
Hi, 

I am unable to replicate it here but on openwisp-controller. It's most probable that fix for it was made recently, so I am closing it, thanks for reporting it! :smile:
