### ISSUE TITLE
[ux] errors made while adding a new device gets hidden 

### ISSUE THREAD

**Issue by atb00ker** [openwisp/django-loci#38]
When adding a new device if someone makes an error of not entering `Geometry` for a `Outdoor environment`, the user will get error `Please correct the errors below.` at the top of the page but the actual field to make the correction is not shown.
The user needs to change the `Type` field then select `Outdoor environment` again to see the errored field.
This may cause confusion to users.

**Comment by nemesisdesign** [comment]
@marfgold1 if you found another bug, please open another bug report (github issue).

**Comment by marfgold1** [comment]
@nemesisdesign i do actually open some issues 😃. Please also check #34 #35 #36 , I already told @atb00ker and he said he want to wait for your review. Thank you 😄
