### ISSUE TITLE
Add support for django 3.0

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/django-loci#47]
Add support for django 3.0, drop django version older than 2.2.

**Comment by atb00ker** [comment]
This can be removed as well : https://github.com/openwisp/django-loci/blob/b731eefe7caf45d65cc7075466a387a3af8e196e/django_loci/channels/base.py#L45

**Comment by oltarzewskik** [comment]
I removed this check here: https://github.com/openwisp/django-loci/pull/51
