### ISSUE TITLE
[qa] Add run-qa-checks, upgrade to openwisp-utils 0.5.1, black formatter

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/django-loci#60]
Add run-qa-checks, upgrade to openwisp-utils 0.5.1 and reformat code with black.

**Comment by morrme** [comment]
I'd like to help with this. I am new to your project.

**Comment by NoumbissiValere** [comment]
welcome to OpenWISP @morrme . Sure, you can work on it. if you haven't yet seen our docs, you read more about the project from http://openwisp.io/docs/

**Comment by nemesisdesign** [comment]
Go for it @morrme, see how it's done in another module to replicate it here, eg: 

- https://github.com/openwisp/django-netjsonconfig/blob/master/run-qa-checks & https://github.com/openwisp/django-netjsonconfig/blob/master/.travis.yml#L28

**Comment by morrme** [comment]
Thank you. I am not familiar with your run-qa-checks. Are you seeking to add the functionality here
https://github.com/openwisp/openwisp-utils/blob/master/run-qa-checks
to your project?
