### ISSUE TITLE
[bug] ignores `is_mobile` False from device

### ISSUE THREAD

**Issue by atb00ker** [openwisp/django-loci#62]
In admin interface:
1. Create a device with a location, set the marker, check `is_mobile` & save.
2. Open it again, uncheck `is_mobile`, save
3. Open the device again and notice `is_mobile` is checked.

**Comment by Purhan** [comment]
I would work on this once https://github.com/openwisp/django-loci/pull/73 is merged.

**Comment by atb00ker** [comment]
Sure! :smile:

**Comment by nemesisdesign** [comment]
@Purhan #73 is merged! :tada:

**Comment by Purhan** [comment]
Thanks, I just created a pull request. This was extremely similar to #65 :smile:
