### ISSUE TITLE
[docs] Add animated gif to README

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/django-loci#69]
Add a brief animated gif which quickly shows:

- add an item to an existing indoor location
- automatic conversion of point to address (after #46 is merged)

**Comment by 2001asjad** [comment]
Hi, I would like to work on this issue. Can you please assign it to me??

**Comment by NoumbissiValere** [comment]
You can go ahead @2001asjad

**Comment by 2001asjad** [comment]
After following all the instructions in the 'Installing for development' section of the README file, whenever I am running migrate in my Command Prompt , I am getting 'Is GDAL installed? If it is, try setting GDAL_LIBRARY_PATH in your settings.'. Can you please help @NoumbissiValere

**Comment by NoumbissiValere** [comment]
@2001asjad please ensure the packages listed [here](https://github.com/openwisp/django-loci/blob/master/.travis.yml#L7) are installed on your system

**Comment by 2001asjad** [comment]
Can you please explain me in more detail that how and what type of GIF do we have to add?
I mean do we have to show adding items in the Locations page or what?

Thank You

**Comment by atb00ker** [comment]
@2001asjad checkout the GIF added here: https://github.com/openwisp/openwisp-radius/blob/master/README.rst

It explores the features in openwisp-radius; gives the user a little brief about what the user gets after successful setup! :smile:

**Comment by nemesisdesign** [comment]
Forgot to close this, sorry. I added some images in the README recently and I think those are good enough. @2001asjad if you want to contribute please look for other issues.
